### ISSUE TITLE
how to use trained model

### ISSUE THREAD

**Issue by everythingnew** [SC4RECOIN/LSTM-Crypto-Price-Prediction#4]
Hi. i used this helpful repo to train my model. now i want to load and use it. could youl tell me please, which part of data do i need for preditct part? do i need just open, close, high,low, and volume? 
do i get close column as the result or is it averaged price?
Thank you

**Comment by SC4RECOIN** [comment]
All the indicators are built from the closing price. If you want to load the model and use it just feed in the same indicators you used to train it and use ```model.predict()```

**Comment by SC4RECOIN** [comment]
You can really use your own indicators. This was built as an example. There are more battle-tested ta libraries that will be much more reliable
